controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - forearm_roll_joint
      - lower_wrist_roll_joint
      - arm_roll_joint
      - upper_wrist_pitch_joint
      - shoulder_yaw_joint
      - palm_roll_joint
      - left_finger_prismatic_joint
    interface_name: position
