trajectory_execution:
  allowed_execution_duration_scaling: 4.0  # Allow 4x the estimated time
  allowed_goal_duration_margin: 2.0        # Add 2 seconds margin
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - finger_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_yaw_joint
      - arm_roll_joint
      - forearm_roll_joint
      - lower_wrist_roll_joint
      - upper_wrist_pitch_joint
      - palm_roll_joint
      
  finger_controller:
    type: GripperCommand
    action_ns: gripper_cmd
    default: true
    joints:
      - left_finger_prismatic_joint-